### ISSUE TITLE
New footer

### ISSUE THREAD

**Issue by thamudi** [jordanopensource/nuha-web#59]
The site now will show a footer with following data displayed:
- Logo
- Title (English and Arabic)
- JOSA copy rights.
- Hyperlinks. The ones marked as "?" leave the href empty for now:
 - Imprint?
 - Terms and policies?
 - Privacy Policy? 
 - Github

![image](https://github.com/jordanopensource/nuha-web/assets/18720062/bea5e3f7-2c45-4069-bcdb-309451d4cc60)

**Comment by itsmohmans** [comment]
Footer for mobile:


![Image](https://github.com/jordanopensource/nuha-web/assets/55551984/f746f1c5-7e5a-4658-8279-a96436a6dcd9)
