### ISSUE TITLE
BUG: Unable to send magic link in the latest release *development*

### ISSUE THREAD

**Issue by thamudi** [jordanopensource/nuha-web#65]
**Bug description and reproduction:**
Go to login > enter your email in the first field for the magic link > submit > page reloads

___ 
**Expected behavior:**
The user should be informed that an email has been sent over to their mail.
___

**Additional details:**

When checking the logs, the following errors show.

![image](https://github.com/jordanopensource/nuha-web/assets/18720062/f44a57c4-45e6-4411-a7e9-4a3125fa7311)

Running the project locally doesn't result in this issue, this issue only occurs when running it through docker or docker compose.

**Comment by mbaraa** [comment]
the user get informed, when the page redirects to the NuxtAuth's confirmation page.

**Comment by thamudi** [comment]
> the user get informed, when the page redirects to the NuxtAuth's confirmation page.

This is the expected behavior, however it is still not happening.
