### ISSUE TITLE
New Navigation

### ISSUE THREAD

**Issue by thamudi** [jordanopensource/nuha-web#66]
We will be working on updating the navigation to contain the following:

- Logo
- Language switcher
- Methodology page hyperlink
- Findings page hyper link (Which will be implemented when the findings are developed.)
- Loging

Refer to the following design for more details:

![image](https://github.com/jordanopensource/nuha-web/assets/18720062/2d9ff7a2-932a-4b48-a475-fa97a954c4bd)

**Comment by itsmohmans** [comment]
Navbar for mobile:


![Image](https://github.com/jordanopensource/nuha-web/assets/55551984/b686500d-616e-41ca-ab51-dcec464cc424)
